import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Accordion,
  Footer,
  Header,
  HeroSection,
  MobileFooter,
  ProductDetail,
  ProductSection,
  RecommendedDropDown,
  TitleWithIcon,
} from "@/src/components";
import { useProductStore } from "@/src/store/ProductStore";
import { useEffect } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

const Home = ({ initialProducts }) => {
  const setProducts = useProductStore((state) => state.setProducts);

  useEffect(() => {
    setProducts(initialProducts);
  }, [initialProducts, setProducts]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <HeroSection />
        <ProductSection />
        <Footer />
        <MobileFooter />
      </main>
    </>
  );
};

export const getServerSideProps = async () => {
  try {
    const response = await axios.get("https://fakestoreapi.com/products");
    const initialProducts = response.data;

    return {
      props: {
        initialProducts,
      },
    };
  } catch (error) {
    console.error("Error fetching the products:", error);
    return {
      props: {
        initialProducts: [],
      },
    };
  }
};

export default Home;
